# Copyright (c) 2025 Max Planck Society
# License: https://bedlam2.is.tuebingen.mpg.de/license.html
#

from pathlib import Path
from typing import NamedTuple

# Globals
CONFIG_ROOT = Path("../../config")
STATS_ROOT = Path("../../stats")

VCAM_ROOT = CONFIG_ROOT / "vcam"
VCAM_CAPTURES = VCAM_ROOT / "vcam_captures.json"

VCAM_TRIM_FRAMES = 30 # trim 1s at start+end
MOTION_STATS_PATH = STATS_ROOT / "motion_stats_training.csv" # body yaw

# Predefined configurations, polar coordinates
# Notes:
#   hfov = 65.470451 : 28mm lens on 36x20.25 DSLR filmback
class ConfigCamera(NamedTuple):
    keyframes:                      int = 2
    hfov_ranges:                    list = [] # list of tuples (hfov_min, hfov_max)
    hfov_mindelta:                  float = -1.0 # Zoom shot randomization mindelta
    hfov_maxdelta:                  float = -1.0 # Zoom shot randomization maxdelta
    sensor_width:                   float = -1.0
    sensor_height:                  float = -1.0
    camera_height_min:              float = 50.0 # negative value will ignore height randomization and use camera height from sequence definition
    camera_height_max:              float = 250.0
    camera_autodistance:            bool = False # calculate distance from HFOV
    camera_autodistance_ref:        float = 200.0 # horizontal distance for HFOV=52, larger values will increase distance to body when calculating distance from HFOV
    static_world_location:          bool = False # static world position camera, does not use SpringArm, use for HDRI where we don't want to reposition camera relative to body
    follow:                         bool = False
    follow_static_location:         bool = False # determine set static camera world position at first valid frame of follow camera
    follow_camera_distance:         float = 100 # when using camera_autodistance value will be used to specify additional randomized offset range when using camera_autodistance
    follow_camera_yaw_offset_min:   float = 270.0
    follow_camera_yaw_offset_max:   float = 270.0
    camera_shake:                   str = ""
    camera_shake_intensity:         float = 1.0
    look_at:                        bool = False
    look_at_interp_speed:           float = 0.5
    look_at_target:                 str = "body_0" # body_0 | cameraroot
    look_at_target_bodyparts:       list = [] # pelvis, spine1, spine2, spine3, neck
    look_at_offset_z:               float = 0.0
    look_at_offset_z_range:         float = 10.0
    randomize_location:             bool = True
    distance_min:                   float = 300.0 # Distance camera to cameraroot. If autodistance_from_hfov is used then this is the offset relative to autodistance
    distance_max:                   float = 500.0
    distance_mindelta:              float = 0.0   # minimal distance between randomized values
    distance_maxdelta:              float = 100.0 # maximal distance between randomized values
    theta_front:                    bool = False # Apply yaw offset to cameraroot so that theta=0 will look at body front
    theta_ranges:                   list = [] # list of tuples (theta_min, theta_max)
    theta_min:                      float = -60.0 # yaw, positive values westwards, not used if theta_ranges is set
    theta_max:                      float = 60.0 # not used if theta_ranges is set
    theta_mindelta:                 float = 30.0  # minimal distance between randomized values
    theta_maxdelta:                 float = 60.0  # maximal distance between randomized values
    phi_min:                        float = -30.0 # pitch, value of 0.0 will be camera at default height, positive values southwards
    phi_max:                        float = 10.0
    phi_mindelta:                   float = 15.0  # minimal distance between randomized values
    phi_maxdelta:                   float = 15.0  # maximal distance between randomized values
    camera_local_y_min:             float = 0.0
    camera_local_y_max:             float = 0.0
    camera_local_y_mindelta:        float = 0.0
    camera_local_y_maxdelta:        float = 0.0
    camera_local_z_min:             float = 0.0
    camera_local_z_max:             float = 0.0
    camera_local_z_mindelta:        float = 0.0
    camera_local_z_maxdelta:        float = 0.0
    camera_local_y_stage:           float = 500.0 # Maximum width of stage for dolly y autodistance y offset calculation
    camera_local_autopitch:         bool = False # Will calculate optimal camera local pitch from camera height and distance
    dolly_types:                    list = [] # x | y | xy
    camera_roll_min:                float = 0.0
    camera_roll_max:                float = 0.0
    vcam:                           bool = False
    vcam_type:                      list = [] # ["stand", "landscape"]
    vcam_focallength_ranges:        list = [] # ["14", "14-28", "28"]
    vcam_reverse:                   bool = False # True will reverse vcam camera sequence
    vcam_theta_front:               bool = True # Apply yaw offset to cameraroot so that theta=0 will look at vcam body front
    vcam_height_offset_min:         float = 0.0 # Minimum height offset to add to vcam camera height
    vcam_height_offset_max:         float = 0.0 # Maximum height offset to add to vcam camera height
    vcam_x_offset_min:              float = 0.0 # Minimum offset to add to vcam camera x axis
    vcam_x_offset_max:              float = 0.0 # Maximum offset to add to vcam camera x axis
    vcam_pitch_offset_min:          float = 0.0 # Minimum offset to add to vcam camera pitch
    vcam_pitch_offset_max:          float = 0.0 # Maximum offset to add to vcam camera pitch

configs_camera_movement = {}

# Default camera configuration
configs_camera_movement["cam_default"] = ConfigCamera()
configs_camera_movement["cam_tracking_hdri"] = ConfigCamera(sensor_width=36.0, sensor_height=36.0, look_at = True, look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_front"] = ConfigCamera(hfov_ranges=[(52.0, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=100, follow_camera_yaw_offset_min=270.0, follow_camera_yaw_offset_max=270.0, look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_randomyaw"] = ConfigCamera(hfov_ranges=[(52.0, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=100, follow_camera_yaw_offset_min=0.0, follow_camera_yaw_offset_max=360.0, look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_18-70"] = ConfigCamera(hfov_ranges=[(28.841545, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=100, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=225.0, follow_camera_yaw_offset_max=315.0, look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_18-70_shake"] = ConfigCamera(hfov_ranges=[(28.841545, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=100, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=225.0, follow_camera_yaw_offset_max=315.0, camera_shake="BE_CameraShake_LowFrequency", look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=200, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=225.0, follow_camera_yaw_offset_max=315.0, camera_shake="BE_CameraShake_LowFrequency", look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_18-50_shake_side"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=200, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=-30, follow_camera_yaw_offset_max=30, camera_shake="BE_CameraShake_LowFrequency", look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_orbit_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", look_at=True, look_at_target="cameraroot", randomize_location=True, distance_min=400, distance_max=600, distance_mindelta=0, distance_maxdelta=100, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=120, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
configs_camera_movement["cam_dolly_y_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", randomize_location=True, distance_min=400, distance_max=600, distance_mindelta=0, distance_maxdelta=0, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-400, camera_local_y_max=-200, camera_local_y_mindelta=500, camera_local_y_maxdelta=600, camera_local_autopitch=True, dolly_types=["y"])
configs_camera_movement["cam_dolly_x_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", randomize_location=True, distance_min=600, distance_max=700, distance_mindelta=400, distance_maxdelta=500, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=0, camera_local_y_max=0, camera_local_y_mindelta=0, camera_local_y_maxdelta=0, camera_local_autopitch=True, dolly_types=["x"])
configs_camera_movement["cam_dolly_xy_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", randomize_location=True, distance_min=600, distance_max=700, distance_mindelta=200, distance_maxdelta=500, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-400, camera_local_y_max=-200, camera_local_y_mindelta=200, camera_local_y_maxdelta=600, camera_local_autopitch=True, dolly_types=["xy"])
configs_camera_movement["cam_follow_18-35_360_shake"] = ConfigCamera(hfov_ranges=[(54.432224, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=200, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=0.0, follow_camera_yaw_offset_max=360.0, camera_shake="BE_CameraShake_LowFrequency", look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_18-70_360_shake"] = ConfigCamera(hfov_ranges=[(28.841545, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=200, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=0.0, follow_camera_yaw_offset_max=360.0, camera_shake="BE_CameraShake_LowFrequency", look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_follow_18-24_shake"] = ConfigCamera(hfov_ranges=[(73.739792, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=50, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=225.0, follow_camera_yaw_offset_max=315.0, camera_shake="BE_CameraShake_LowFrequency", look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=False)
configs_camera_movement["cam_follow_10-18_180_shake"] = ConfigCamera(hfov_ranges=[(90.0, 121.890785)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_camera_distance=50, camera_autodistance_ref=180.0, follow_camera_yaw_offset_min=180.0, follow_camera_yaw_offset_max=360.0, camera_shake="BE_CameraShake_LowFrequency", look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=False)

# Long-lens on tripod, limit height to [50, 180]
configs_camera_movement["cam_400mm_stadium"] = ConfigCamera(hfov_ranges=[(5.153143, 5.153143)], sensor_width=36.0, sensor_height=20.25, camera_height_min=50, camera_height_max=180, camera_autodistance=True, follow=True, follow_static_location=True, follow_camera_distance=100.0, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=225.0, follow_camera_yaw_offset_max=315.0, look_at_target="body_0", randomize_location=False)

# AIUE_10_04, min height=100
configs_camera_movement["cam_dolly_xy_18-35_shake_ai1004"] = ConfigCamera(hfov_ranges=[(54.432224, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_height_min=100.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", randomize_location=True, distance_min=300, distance_max=400, distance_mindelta=50, distance_maxdelta=100, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-100, camera_local_y_max=100, camera_local_y_mindelta=50, camera_local_y_maxdelta=100, camera_local_autopitch=True, dolly_types=["xy"])
configs_camera_movement["cam_orbit_18-35_shake_ai1004"] = ConfigCamera(hfov_ranges=[(54.432224, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_height_min=100.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=1.0, look_at=True, look_at_target="cameraroot", randomize_location=True, distance_min=300, distance_max=1000, distance_mindelta=0, distance_maxdelta=50, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=120, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
configs_camera_movement["cam_orbit_18-28_shake_ai1004"] = ConfigCamera(hfov_ranges=[(65.470451, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_height_min=100.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=True, look_at_target="cameraroot", randomize_location=True, distance_min=300, distance_max=1000, distance_mindelta=0, distance_maxdelta=50, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=90, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)

# AIUE_08_05, min height=100
configs_camera_movement["cam_orbit_18-28_shake_ai0805"] = ConfigCamera(hfov_ranges=[(65.470451, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_height_min=100.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=1.0, look_at=True, look_at_target="cameraroot", randomize_location=True, distance_min=200, distance_max=400, distance_mindelta=0, distance_maxdelta=50, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=120, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
  # Portrait mode, high frequency shake
configs_camera_movement["cam_orbit_18-28_shake_ai0805_portrait"] = ConfigCamera(hfov_ranges=[(65.470451, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_height_min=140.0, camera_height_max=200.0, follow=False, camera_shake="BE_CameraShake_HighFrequency", camera_shake_intensity=0.5, look_at=True, look_at_interp_speed=1.0, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=200, distance_max=350, distance_mindelta=0, distance_maxdelta=20, theta_min=0, theta_max=360, theta_mindelta=45, theta_maxdelta=90, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=90, camera_roll_max=90)

# BE_YogaStudio
configs_camera_movement["cam_yogastudio_orbit_18-35_shake"] = ConfigCamera(hfov_ranges=[(54.432224, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", look_at=True, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=450, distance_max=500, distance_mindelta=0, distance_maxdelta=50, theta_min=0, theta_max=360, theta_mindelta=90, theta_maxdelta=360, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
configs_camera_movement["cam_yogastudio_static_18-40"] = ConfigCamera(hfov_ranges=[(48.455490, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=True, follow_static_location=True, follow_camera_distance=10.0, camera_autodistance_ref=180.0, follow_camera_yaw_offset_min=0, follow_camera_yaw_offset_max=360.0, look_at_target="body_0", randomize_location=False)

# BE_CitySample
configs_camera_movement["cam_citysample_orbit_24-105_shake"] = ConfigCamera(hfov_ranges=[(19.455156, 73.739792)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=False, camera_shake="BE_CameraShake_LowFrequency", look_at=True, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=-100, distance_max=100, distance_mindelta=0, distance_maxdelta=200, theta_min=0, theta_max=360, theta_mindelta=90, theta_maxdelta=360, phi_min=-8, phi_max=0, phi_mindelta=0, phi_maxdelta=8)
configs_camera_movement["cam_citysample_dolly_xy_24-28-35-50_shake"] = ConfigCamera(hfov_ranges=[(73.739792,73.739792), (65.470451,65.470451), (54.432224,54.432224), (39.597752,39.597752)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=0, distance_max=500, distance_mindelta=100, distance_maxdelta=400, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-100, camera_local_y_max=100, camera_local_y_mindelta=50, camera_local_y_maxdelta=100, camera_local_y_stage=100, camera_local_autopitch=True, dolly_types=["x", "y", "xy"])
configs_camera_movement["cam_citysample_orbit_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", look_at=True, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=500, distance_max=1000, distance_mindelta=100, distance_maxdelta=300, theta_min=0, theta_max=360, theta_mindelta=90, theta_maxdelta=180, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
configs_camera_movement["cam_citysample_dolly_xy_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=0, distance_max=500, distance_mindelta=100, distance_maxdelta=400, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-100, camera_local_y_max=100, camera_local_y_mindelta=50, camera_local_y_maxdelta=100, camera_local_y_stage=0, camera_local_autopitch=True, dolly_types=["x", "y", "xy"])
configs_camera_movement["cam_citysample_dolly_z_28-70_shake"] = ConfigCamera(hfov_ranges=[(28.841545, 65.470451)], sensor_width=36.0, sensor_height=20.25, camera_height_min=0, camera_height_max=0, camera_autodistance=True, camera_autodistance_ref=240.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=True, look_at_target="cameraroot", look_at_offset_z=50.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=-100, distance_max=100, distance_mindelta=0, distance_maxdelta=200, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_z_min=0, camera_local_z_max=1000, camera_local_z_mindelta=500, camera_local_z_maxdelta=1000, camera_local_autopitch=False, dolly_types=["z"])
configs_camera_movement["cam_citysample_dolly_xy_18-70_shake"] = ConfigCamera(hfov_ranges=[(28.841545, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, camera_autodistance_ref=150, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", look_at_offset_z=120.0, look_at_offset_z_range=10.0, randomize_location=True, distance_min=0, distance_max=600, distance_mindelta=200, distance_maxdelta=600, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-200, camera_local_y_max=200, camera_local_y_mindelta=150, camera_local_y_maxdelta=400, camera_local_y_stage=0, camera_local_autopitch=True, dolly_types=["x", "y", "xy"])

# BE_IBL/MOYO
configs_camera_movement["cam_hdri"] = ConfigCamera(static_world_location=True, sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, follow=False, look_at=True, look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_hdri_18-50_shake"] = ConfigCamera(static_world_location=True, hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, follow=False, look_at=True, look_at_target="body_0", look_at_offset_z=0.0, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=1.0, randomize_location=False)
configs_camera_movement["cam_hdri_80-120_shake"] = ConfigCamera(static_world_location=True, hfov_ranges=[], sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, randomize_location=False)
configs_camera_movement["cam_hdri_18-120"] = ConfigCamera(static_world_location=True, hfov_ranges=[], sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=False)
configs_camera_movement["cam_hdri_50-100"] = ConfigCamera(static_world_location=True, hfov_ranges=[], camera_height_min=-1, camera_height_max=-1, sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=False)
configs_camera_movement["cam_hdri_18-100"] = ConfigCamera(static_world_location=True, hfov_ranges=[], camera_height_min=-1, camera_height_max=-1, sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=False)

# BE_Stadium, long-lens on tripod, limit height to [100, 200]
configs_camera_movement["cam_stadium_100-400"] = ConfigCamera(hfov_ranges=[(5.153143, 20.407946)], sensor_width=36.0, sensor_height=20.25, camera_height_min=100, camera_height_max=200, camera_autodistance=True, follow=True, follow_static_location=True, follow_camera_distance=100.0, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=0.0, follow_camera_yaw_offset_max=360.0, look_at_target="body_0", randomize_location=False)
configs_camera_movement["cam_stadium_100-400_roll"] = ConfigCamera(hfov_ranges=[(5.153143, 20.407946)], sensor_width=36.0, sensor_height=20.25, camera_height_min=100, camera_height_max=200, camera_autodistance=True, follow=True, follow_static_location=True, follow_camera_distance=100.0, camera_autodistance_ref=220.0, follow_camera_yaw_offset_min=0.0, follow_camera_yaw_offset_max=360.0, look_at_target="body_0", randomize_location=False, camera_roll_min=-1, camera_roll_max=1)

# BE_BusStation
configs_camera_movement["cam_busstation_orbit_18-35_shake"] = ConfigCamera(hfov_ranges=[(54.432224, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", look_at=True, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=500, distance_max=600, distance_mindelta=0, distance_maxdelta=50, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=90, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
configs_camera_movement["cam_busstation_orbit_18-35_shake05"] = ConfigCamera(hfov_ranges=[(54.432224, 90.0)], sensor_width=36.0, sensor_height=20.25, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=True, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=500, distance_max=600, distance_mindelta=0, distance_maxdelta=50, theta_min=0, theta_max=360, theta_mindelta=15, theta_maxdelta=60, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
configs_camera_movement["cam_busstation_orbit_zoom_18-70"] = ConfigCamera(hfov_ranges=[(28.841545, 90.0)], hfov_mindelta=30, hfov_maxdelta=60, sensor_width=36.0, sensor_height=20.25, camera_height_min=150, camera_height_max=200, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.25, look_at=True, look_at_interp_speed=2.0, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=700, distance_max=1000, distance_mindelta=0, distance_maxdelta=100, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=45, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)

# BE_ArchmodelsVol8
configs_camera_movement["cam_archmodels8_dolly_xy_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_autodistance=True, camera_autodistance_ref=150, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", look_at_offset_z=120.0, look_at_offset_z_range=10.0, randomize_location=True, distance_min=0, distance_max=400, distance_mindelta=200, distance_maxdelta=400, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-200, camera_local_y_max=200, camera_local_y_mindelta=150, camera_local_y_maxdelta=400, camera_local_y_stage=0, camera_local_autopitch=True, dolly_types=["x", "y", "xy"])
configs_camera_movement["cam_archmodels8_dolly_z_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, camera_height_min=0, camera_height_max=0, camera_autodistance=True, camera_autodistance_ref=200.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=True, look_at_target="cameraroot", look_at_offset_z=100.0, look_at_offset_z_range=10.0, randomize_location=True, distance_min=-50, distance_max=50, distance_mindelta=0, distance_maxdelta=100, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=45, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_z_min=0, camera_local_z_max=500, camera_local_z_mindelta=200, camera_local_z_maxdelta=500, camera_local_autopitch=False, dolly_types=["z"])
configs_camera_movement["cam_archmodels8_zoom_18-50"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], hfov_mindelta=25, hfov_maxdelta=50, sensor_width=36.0, sensor_height=20.25, camera_height_min=150, camera_height_max=200, camera_autodistance=False, follow=False, look_at=True, look_at_interp_speed=1.0, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=550, distance_max=650, distance_mindelta=0, distance_maxdelta=0, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=-3, camera_roll_max=3)

# BE_AI_UE5_vol09_01
configs_camera_movement["cam_static_14-18_ai0901"] = ConfigCamera(hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, camera_height_min=130.0, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=170, distance_max=250, distance_mindelta=0, distance_maxdelta=20, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=-3, camera_roll_max=3)
  # Portrait mode, high frequency shake
configs_camera_movement["cam_orbit_14-24_shake_ai0901"] = ConfigCamera(hfov_ranges=[(73.739792, 104.250031)], sensor_width=36.0, sensor_height=20.25, camera_height_min=140.0, camera_height_max=200.0, follow=False, camera_shake="BE_CameraShake_HighFrequency", camera_shake_intensity=1.0, look_at=True, look_at_interp_speed=1.0, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=170, distance_max=250, distance_mindelta=0, distance_maxdelta=20, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=60, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=90, camera_roll_max=90)
  # Portrait mode, static cam focussing on front body
configs_camera_movement["cam_static_14-28_static_ai0901"] = ConfigCamera(hfov_ranges=[(65.470451, 104.250031)], sensor_width=36.0, sensor_height=20.25, camera_height_min=120, camera_height_max=160, camera_autodistance=True, follow=True, follow_static_location=True, follow_camera_distance=10.0, camera_autodistance_ref=100.0, follow_camera_yaw_offset_min=265.0, follow_camera_yaw_offset_max=275.0, look_at_target="body_0", look_at_target_bodyparts=["spine3", "neck"], randomize_location=False, camera_roll_min=89, camera_roll_max=91)

   # VCam
#configs_camera_movement["cam_vcam_12_orbit_ai0901"] = ConfigCamera(vcam_reverse=False, vcam="vcam_20240716_0003_orbit.json", hfov_ranges=[(112.61986541748047, 112.61986541748047)], sensor_width=36.0, sensor_height=20.25)
  # 14, front-facing +-30
configs_camera_movement["cam_vcam_14-28_ai0805"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["stand", "landscape"], vcam_focallength_ranges=["14","14-28","28"], hfov_ranges=[(104.250031, 104.250031),(65.470451, 104.250031),(65.470451, 65.470451)], sensor_width=36.0, sensor_height=20.25, theta_min=-30, theta_max=30)
configs_camera_movement["cam_vcam_14-28_ai0805_reverse"] = ConfigCamera(vcam=True, vcam_reverse=True, vcam_type = ["stand", "landscape"], vcam_focallength_ranges=["14","14-28","28"], hfov_ranges=[(104.250031, 104.250031),(65.470451, 104.250031),(65.470451, 65.470451)], sensor_width=36.0, sensor_height=20.25, theta_min=-60, theta_max=60)
configs_camera_movement["cam_vcam_14-18_ai1004_portrait"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["stand", "portrait"], vcam_focallength_ranges=["14"], hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-45, theta_max=45)
configs_camera_movement["cam_vcam_14-18_ai1101_portrait"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["stand", "portrait"], vcam_focallength_ranges=["14"], hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-60, theta_max=60)
configs_camera_movement["cam_vcam_14-18_ai1105_landscape"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["stand", "landscape"], vcam_focallength_ranges=["14"], hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-60, theta_max=60)
configs_camera_movement["cam_vcam_14-18_ai1102_portrait"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["stand", "portrait"], vcam_focallength_ranges=["14"], hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-90, theta_max=90)
configs_camera_movement["cam_vcam_14-18_ai1102_landscape"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["stand_avp", "landscape"], vcam_focallength_ranges=["0"], hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-120, theta_max=120)

# BE_Rome
configs_camera_movement["cam_rome_dolly_z_zoom_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], hfov_mindelta=15, hfov_maxdelta=30, sensor_width=36.0, sensor_height=20.25, camera_height_min=130, camera_height_max=170, camera_autodistance=False, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=True, look_at_target="cameraroot", look_at_offset_z=130.0, look_at_offset_z_range=10.0, randomize_location=True, distance_min=500, distance_max=800, distance_mindelta=0, distance_maxdelta=0, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_z_min=0, camera_local_z_max=500, camera_local_z_mindelta=200, camera_local_z_maxdelta=400, camera_local_autopitch=False, dolly_types=["z"])
configs_camera_movement["cam_rome_orbit_zoom_18-50"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], hfov_mindelta=25, hfov_maxdelta=50, sensor_width=36.0, sensor_height=20.25, camera_height_min=150, camera_height_max=200, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.25, look_at=True, look_at_interp_speed=2.0, look_at_target="body_0", look_at_target_bodyparts=["pelvis", "spine1", "spine2", "spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=500, distance_max=800, distance_mindelta=0, distance_maxdelta=100, theta_min=0, theta_max=360, theta_mindelta=30, theta_maxdelta=45, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
configs_camera_movement["cam_rome_dolly_xy_zoom_18-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 90.0)], hfov_mindelta=15, hfov_maxdelta=30, sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, camera_autodistance_ref=0.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", look_at_offset_z=140.0, look_at_offset_z_range=10.0, randomize_location=True, distance_min=200, distance_max=500, distance_mindelta=150, distance_maxdelta=300, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-200, camera_local_y_max=200, camera_local_y_mindelta=150, camera_local_y_maxdelta=300, camera_local_y_stage=0, camera_local_autopitch=True, dolly_types=["x", "y", "xy"])
configs_camera_movement["cam_vcam_14-24_rome_portrait"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["stand", "portrait"], vcam_focallength_ranges=["14"], hfov_ranges=[(73.739792, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-90, theta_max=90)
configs_camera_movement["cam_vcam_14-18_rome_orbit_portrait"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["orbit", "portrait"], vcam_focallength_ranges=["14"], hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-30, theta_max=30)
configs_camera_movement["cam_vcam_14-24_rome_approachshort"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["approachshort", "landscape"], vcam_focallength_ranges=["14"], hfov_ranges=[(73.739792, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-60, theta_max=60)

# BE_ChemicalPlant
configs_camera_movement["cam_chemicalplant_dolly_z_zoom_14-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 104.250031)], hfov_mindelta=15, hfov_maxdelta=30, sensor_width=36.0, sensor_height=20.25, camera_height_min=130, camera_height_max=170, camera_autodistance=False, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=1.0, look_at=True, look_at_target="cameraroot", look_at_offset_z=80.0, look_at_offset_z_range=10.0, randomize_location=True, distance_min=400, distance_max=800, distance_mindelta=0, distance_maxdelta=0, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_z_min=0, camera_local_z_max=400, camera_local_z_mindelta=100, camera_local_z_maxdelta=300, camera_local_autopitch=False, dolly_types=["z"])
configs_camera_movement["cam_vcam_14-28_chemicalplant_approach_portrait"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["approach", "portrait"], vcam_focallength_ranges=["14"], hfov_ranges=[(65.470451, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-90, theta_max=90)
configs_camera_movement["cam_chemicalplant_dolly_xy_zoom_14-50_shake"] = ConfigCamera(hfov_ranges=[(39.597752, 104.250031)], hfov_mindelta=15, hfov_maxdelta=30, sensor_width=36.0, sensor_height=20.25, camera_autodistance=False, camera_autodistance_ref=0.0, follow=False, camera_shake="BE_CameraShake_LowFrequency", camera_shake_intensity=0.5, look_at=False, look_at_target="cameraroot", look_at_offset_z=140.0, look_at_offset_z_range=10.0, randomize_location=True, distance_min=200, distance_max=500, distance_mindelta=150, distance_maxdelta=300, theta_min=0, theta_max=360, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_local_y_min=-150, camera_local_y_max=150, camera_local_y_mindelta=150, camera_local_y_maxdelta=250, camera_local_y_stage=0, camera_local_autopitch=True, dolly_types=["x", "y", "xy"])
configs_camera_movement["cam_vcam_avp_14-18_chemicalplant_orbit_landscape"] = ConfigCamera(vcam=True, vcam_reverse=False, vcam_type = ["orbit_avp", "landscape"], vcam_focallength_ranges=["0"], hfov_ranges=[(90.0, 104.250031)], sensor_width=36.0, sensor_height=20.25, theta_min=-45, theta_max=45)

# BE_Yakohama, approach to group stage (vcam_use_cameraroot_offset=False), +-20cm height offset
configs_camera_movement["cam_vcam_avp_18-50_yakohama_approach_landscape"] = ConfigCamera(vcam_theta_front=False, vcam=True, vcam_reverse=False, vcam_type = ["approach_avp", "landscape"], vcam_focallength_ranges=["0"], vcam_height_offset_min=-20, vcam_height_offset_max=20, vcam_x_offset_min=-450, vcam_x_offset_max=-550, hfov_ranges=[(39.597752, 90.0)], sensor_width=36.0, sensor_height=20.25, theta_ranges=[(-10, 10), (170, 190)], theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)

# Upper body
configs_camera_movement["cam_static_28-35_ai1105"] = ConfigCamera(hfov_ranges=[(54.432224, 65.470451)], sensor_width=36.0, sensor_height=20.25, camera_height_min=140.0, camera_height_max=200.0, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["neck", "head"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=180, distance_max=200, distance_mindelta=0, distance_maxdelta=0, theta_front=True, theta_min=-15, theta_max=15, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=-3, camera_roll_max=3)
configs_camera_movement["cam_static_50-80_yakohama"] = ConfigCamera(hfov_ranges=[(25.360765, 39.597752)], sensor_width=36.0, sensor_height=20.25, camera_height_min=140.0, camera_height_max=200.0, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["neck", "head"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=450, distance_max=500, distance_mindelta=0, distance_maxdelta=0, theta_front=True, theta_min=-30, theta_max=30, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=-3, camera_roll_max=3)
configs_camera_movement["cam_static_80-200_chemicalplant"] = ConfigCamera(hfov_ranges=[(10.285529, 25.360765)], hfov_mindelta=7, hfov_maxdelta=15, sensor_width=36.0, sensor_height=20.25, camera_height_min=140.0, camera_height_max=200.0, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["head"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=550, distance_max=600, distance_mindelta=0, distance_maxdelta=0, theta_front=True, theta_min=-45, theta_max=45, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=-3, camera_roll_max=3)

# BE_MiddleEast
#   upper body, long zoom shots, theta_min/theta_max defined in be_seq.csv
configs_camera_movement["cam_120-300_middleeast_landscape"] = ConfigCamera(hfov_ranges=[(6.867261, 17.061531)], hfov_mindelta=5, hfov_maxdelta=10.1, sensor_width=36.0, sensor_height=20.25, camera_height_min=140.0, camera_height_max=200.0, follow=False, look_at=True, look_at_target="body_0", look_at_target_bodyparts=["spine3", "neck"], look_at_offset_z=0.0, look_at_offset_z_range=5.0, randomize_location=True, distance_min=1400, distance_max=1500, distance_mindelta=0, distance_maxdelta=0, theta_min=0, theta_max=0, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0, camera_roll_min=-3, camera_roll_max=3)

configs_camera_movement["cam_vcam_28-50_middleeast_approach_landscape"] = ConfigCamera(hfov_ranges=[(39.597752, 65.470451)], hfov_mindelta=0, hfov_maxdelta=0, vcam_theta_front=False, vcam=True, vcam_reverse=False, vcam_type = ["approach", "landscape"], vcam_focallength_ranges=["14"], vcam_height_offset_min=-10, vcam_height_offset_max=10, vcam_x_offset_min=-400, vcam_x_offset_max=-700, vcam_pitch_offset_min=8, vcam_pitch_offset_max=12, sensor_width=36.0, sensor_height=20.25, theta_mindelta=0, theta_maxdelta=0, phi_min=0, phi_max=0, phi_mindelta=0, phi_maxdelta=0)
